baseURL = 'https://pleeq.com/blog/public/'
languageCode = 'en-us'
title = 'Pleeq Software Blog'
theme = "paper"
 
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
		[markup.goldmark.parser]
			autoHeadingID = true
			[markup.goldmark.parser.attribute]
				block = true
