baseURL = 'https://pleeq.com/alexander_deplov_portfolio/alex_deplov/'
languageCode = 'en-us'
title = 'Alexander Deplov: Senior Product Designer Portfolio'
theme = 'Paper'

[params]
color = 'linen'

mastodon = 'https://mastodon.social/@alex_deplov'
rss = true

# home page profile
  #avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  #name = 'Alex Deplov'
  #bio = 'Bio text'

# misc
  disableHLJS = false                       # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  #monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon