baseURL = "https://pleeq.com/ai-hot-news/"
languageCode = "en-us"
title = "AI Hot News"
theme = "ai-hot-news-theme"
publishDir = "."

[permalinks]
  posts = "/:slug.html"

[params]
  author = "James Smith"